name: CI Testapp

on:
    push:

jobs:
    lint:
        name: 'Lint code'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install --frozen-lockfile

            - name: Build
              run: npm run build

            - name: Check lint
              run: npm run lint
    deploy:
      runs-on: ubuntu-latest

      steps:
          # Krok 1: Checkout repozitáře
          - name: Checkout repository
            uses: actions/checkout@v4

          # Krok 2: Nastavení SSH klíče
          - name: Set up SSH key
            run: |
                mkdir -p ~/.ssh
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H 3depox.cz >> ~/.ssh/known_hosts  # Přidání host key pro 3depox.cz

          # Krok 3: Připojení na server a nasazení aplikace
          - name: Deploy over SSH
            run: |
                ssh -i ~/.ssh/id_rsa -t karelpelcak@3depox.cz << 'EOF'
                  cd /path/to/your/repo/test-app
                  git pull origin main
                  docker stop testapp-container || true
                  docker rm testapp-container || true
                  docker build -t nextjs-app .
                  docker run -d -p 5173:5173 --name testapp-container nextjs-app
                EOF
