name: CI Testapp

on:
    push:

jobs:
    lint:
        name: 'Lint code'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install --frozen-lockfile

            - name: Build
              run: npm run build

            - name: Check lint
              run: npm run lint
  deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup SSH
          run: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H 3depox.cz >> ~/.ssh/known_hosts

          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Deploy over SSH
          run: |
            ssh -i ~/.ssh/id_rsa karelpelcak@3depox.cz << 'EOF'
              cd cd ./repo/test-app
              git pull 
              docker stop testapp-container || true
              docker rm testapp-container || true
              docker build -t nextjs-app .
              docker run -d -p 5173:5173 --name testapp-container nextjs-app
            EOF